name: idle_timer_example
description: Example app for idle_timer plugin

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_idle_detector:
    path: ../

flutter:
  uses-material-design: true
